# Generated by Django 4.1.2 on 2022-10-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_essence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essence',
            name='date',
            field=models.DateField(verbose_name='Absorbtion Date'),
        ),
    ]
