# Generated by Django 4.1.2 on 2022-10-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_essence_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essence',
            old_name='amount',
            new_name='absorbtions',
        ),
    ]
