# Generated by Django 4.1.2 on 2022-10-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_enemy_remove_zerg_mutations_delete_mutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerg',
            name='enemies',
            field=models.ManyToManyField(to='main_app.enemy'),
        ),
    ]
